# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbZCuT29-iefkyJz3bf9gS924MxiZpV2
"""

# config.py

PARAMS = {
    "modo_bl": True,                 # True = usar búsqueda local
    "aco_version": 2,               # 1, 2, 3 o 4

    "nivel_saturacion": 100,       # 50, 75, 100

    "num_hormigas": 500,           # 50, 100, 500, 1000

    "evaporacion": 0.2,
    "q0": 0.4,                    # valores permitidos: 0.4, 0.6, 0.8, 0.9
    "alpha": 2,                   # influencia de la feromona
    "beta": 0.5,                  # influencia de la información heurística

    "seed": 3,                   # Semilla para reproducibilidad

}

