# -*- coding: utf-8 -*-
"""constantes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zt5YmXbeC65IYIVRXnTm7dEWOY66Big
"""


#franja = 0 # a partir de las 12 am
franja = 1 # a partir de las 6am

if franja==0:
    procesos_por_prioridad = {
            1: [['ENF', 2, 20, 30, 75],
                ['CON',1, 10, 20, 25],
                ['LAB', 1, 20,35,45],
                ['RAY',1, 3, 5, 15],
                ['ENF', 2,  20,30, 40],
                ['CON', 1, 20,30, 40]],
            2: [['ENF', 2, 18, 28, 45],
                ['CON',1, 10, 20, 25],
                ['LAB', 1, 3, 5, 15],
                ['RAY',1, 5, 10, 20],
                ['ENF', 2, 15, 20, 30],
                ['CON', 1, 15, 20, 25 ]],
            3: [['ENF', 1, 15, 22, 30],
                ['CON',1, 5, 15, 20],
                ['LAB', 1, 3, 5, 15],
                ['RAY',1, 5, 10, 20],
                ['ENF', 1, 10, 15, 20],
                ['CON', 1, 8, 15, 18]],
            4: [['ENF', 1, 5, 10, 20],
                ['ACON',1, 2, 3, 5],
                ['RAY',1, 2, 5, 10],
                ['ENF', 1, 5, 8, 12 ],
                ['ACON', 1, 5, 10, 15]],
            5: [['ENF', 1, 2, 4, 8],
                ['ACON',1, 2, 3, 5]]
      }
    TR={'CON':2,'ENF':9,'RAY':1,'LAB':1 ,'ACON':2}
    R=['CON1','CON2','ENF1','ENF2','ENF3','ENF4','ENF5','ENF6','ENF7','ENF8','ENF9','RAY','LAB','ACON1','ACON2']

else:
    procesos_por_prioridad = {
          1: [['ENF', 2, 20, 30, 75],
              ['CON',1, 10, 20, 25],
              ['LAB', 1, 20,35,45],
              ['RAY',1, 3, 5, 15],
              ['ENF', 2,  20,30, 40],
              ['CON', 1, 20,30, 40]],
          2: [['ENF', 2, 18, 28, 45],
              ['CON',1, 10, 20, 25],
              ['LAB', 1, 3, 5, 15],
              ['RAY',1, 5, 10, 20],
              ['ENF', 2, 15, 20, 30],
              ['CON', 1, 15, 20, 25 ]],
          3: [['ENF', 1, 15, 22, 30],
              ['CON',1, 5, 15, 20],
              ['LAB', 1, 3, 5, 15],
              ['RAY',1, 5, 10, 20],
              ['ENF', 1, 10, 15, 20],
              ['CON', 1, 8, 15, 18]],
          4: [['ENF', 1, 5, 10, 20],
              ['CON',1, 2, 3, 5],
              ['RAY',1, 2, 5, 10],
              ['ENF', 1, 5, 8, 12 ],
              ['CON', 1, 5, 10, 15]],
          5: [['ENF', 1, 2, 4, 8],
              ['CON',1, 2, 3, 5]]
    }
    TR={'CON':1,'ENF':6,'RAY':1,'LAB':1}
    R=['CON1','ENF1','ENF2','ENF3','ENF4','ENF5','ENF6','RAY','LAB']

TEPCOF = {'1':0, '2': 15, '3':60, '4':120, '5': 240}
CR ={'CON':1,'ENF':1,'RAY':1,'LAB':float('inf') ,'ACON':1} # Capacidad de los recursos